- ros_topic_name: "scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS  # BIDIRECTIONAL or ROS_TO_GZ
  spawn:
    x: 5.0
    y: 5.0
    z: 0.5
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  entity_name: "arm"
  sdf_file: "$(pwd)/src/my_robot_pkg/worlds/robot.sdf"
